"""initial schema

Revision ID: ea3f8cf5dade
Revises: 
Create Date: 2026-06-14 21:09:40.296921
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea3f8cf5dade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ticket_point', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_snapshots_captured_at'), ['captured_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=True)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('window_gap_warning', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enc_token', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('real_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('shop', sa.String(length=120), nullable=False),
    sa.Column('machine', sa.String(length=120), nullable=True),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_date_raw', sa.String(length=8), nullable=False),
    sa.Column('occurred_time_raw', sa.String(length=8), nullable=False),
    sa.Column('base_hash', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('attribution_status', sa.String(length=16), nullable=False),
    sa.Column('attributed_member_id', sa.Integer(), nullable=True),
    sa.Column('attributed_by', sa.Integer(), nullable=True),
    sa.Column('attributed_at', sa.DateTime(), nullable=True),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attributed_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['attributed_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('real_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_real_transactions_attributed_member_id'), ['attributed_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_real_transactions_attribution_status'), ['attribution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_real_transactions_base_hash'), ['base_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_real_transactions_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_real_transactions_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_member_id'), ['member_id'], unique=False)

    op.create_table('attribution_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_txn_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['real_txn_id'], ['real_transactions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attribution_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribution_claims_real_txn_id'), ['real_txn_id'], unique=False)
        batch_op.create_index('uq_claim_pending_per_txn', ['real_txn_id', 'member_id'], unique=True, sqlite_where=sa.text("status='pending'"))

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('money_nt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('transfer_group_id', sa.String(length=36), nullable=True),
    sa.Column('source_real_txn_id', sa.Integer(), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(entry_type='TOPUP' AND points_delta>0 AND money_nt IS NOT NULL) OR (entry_type='PLAY' AND points_delta<0) OR (entry_type='TRANSFER_IN' AND points_delta>0) OR (entry_type='TRANSFER_OUT' AND points_delta<0) OR (entry_type='ADJUSTMENT' AND points_delta<>0)", name='ck_ledger_entry_sign'),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['source_real_txn_id'], ['real_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_source_real_txn_id'), ['source_real_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transfer_group_id'), ['transfer_group_id'], unique=False)
        batch_op.create_index('ix_ledger_member_created', ['member_id', 'created_at'], unique=False)
        batch_op.create_index('uq_ledger_source_real_active', ['source_real_txn_id'], unique=True, sqlite_where=sa.text('source_real_txn_id IS NOT NULL AND reversal_of_id IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('uq_ledger_source_real_active', sqlite_where=sa.text('source_real_txn_id IS NOT NULL AND reversal_of_id IS NULL'))
        batch_op.drop_index('ix_ledger_member_created')
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transfer_group_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_source_real_txn_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_member_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('attribution_claims', schema=None) as batch_op:
        batch_op.drop_index('uq_claim_pending_per_txn', sqlite_where=sa.text("status='pending'"))
        batch_op.drop_index(batch_op.f('ix_attribution_claims_real_txn_id'))

    op.drop_table('attribution_claims')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_member_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('real_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_real_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_real_transactions_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_real_transactions_base_hash'))
        batch_op.drop_index(batch_op.f('ix_real_transactions_attribution_status'))
        batch_op.drop_index(batch_op.f('ix_real_transactions_attributed_member_id'))

    op.drop_table('real_transactions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('sync_state')
    op.drop_table('sync_runs')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_email'))

    op.drop_table('members')
    op.drop_table('app_settings')
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_snapshots_captured_at'))

    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
